name: Deploy Frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.14.0'

    - name: Install OpenConnect (if VPN is required)
      run: sudo apt-get install -y openconnect

    - name: Connect to VPN (if required)
      run: |
        echo "${{ secrets.VPN_PASSWORD }}" | sudo openconnect \
          --protocol=gp \
          --user="${{ secrets.VPN_USER }}" \
          --passwd-on-stdin \
          ${{ secrets.VPN_HOST }} -b
      env:
        VPN_USER: ${{ secrets.VPN_USER }}
        VPN_PASSWORD: ${{ secrets.VPN_PASSWORD }}
        VPN_HOST: ${{ secrets.VPN_HOST }}

    - name: Install Project Dependencies
      run: npm install

    - name: Build Frontend
      run: npm run build

    - name: Deploy Frontend to Server
      run: |
        sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
          cd /var/personigrama/personigramaUnibagueFrontend || exit;
          git pull;
          npm install;
          npm run build"

    - name: Restart Frontend Service
      run: |
        sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
          cd /var/personigrama/personigramaUnibagueFrontend;
          npm install;
          npm run build;
          pm2 restart react-app || pm2 serve build 3000 --name react-app;
          pm2 save"
